repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.6
    hooks:
      - id: ruff
        args: [src/, tests/, --fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, src/pyoptex, tests]
        pass_filenames: false
  - repo: local
    hooks:
      - id: sync-citation
        name: citation version check
        entry: make check-citation
        language: system
        files: (^src/pyoptex/__init__\.py$|^CITATION\.cff$)
        pass_filenames: false
